### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Xolisani-Mthimunye**
Hi Interviewer,

Kindly see my solution to the Anycompany ordering app.

What I did.
*1 create a back-end
*2 used Spring Boot as the JAVA framework
*3 Used Bootstarp 5 as my front end
*4 Included Sample Data
*5. Used JAVA JDK 17
*6. Used JavaScript for Form processing

I would like to continue working on the solution before the interview process and send a second PR.
What I would like to present:

1. Unit Testing
2. Better logic for the API
3. Document Solution
4. Further Refactoring

Thank YouXolisani

### CODE REVIEW

**Comment by LindaShole** [comment]
Hi Xolisani,
This to acknowledge your pull request.
It will be reviewed and next steps will be communicated promptly.

Thank you

**Comment by Xolisani-Mthimunye** [comment]
Hi Linda,

Thanks for the acknowledgment message.

Did not realise this PR was still open.

I am ready may we kindly proceed with the next steps"

**Comment by Xolisani-Mthimunye** [comment]
> Hi Linda,
> 
> Thanks for the acknowledgment message.
> 
> Did not realise this PR was still open.
> 
> I am ready may we kindly proceed with the next steps"

Hi Linda,

Thanks for the acknowledgment message.

Did not realise this PR was still open.

I am ready may we kindly proceed with the next steps"

**Comment by LindaShole** [comment]
It was good reviewing your code.
Thank you

**Pull request closed without merging**
